
const {
    REACT_APP_API_PROTOCOL,
    REACT_APP_API_HOST,
    REACT_APP_API_PORT,
    REACT_APP_API_CONTEXT,
} = process.env

export const ENDPOINT = `${REACT_APP_API_PROTOCOL}://${REACT_APP_API_HOST}:${REACT_APP_API_PORT}/${REACT_APP_API_CONTEXT}/`;;;
